In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

In [2]:
path=pd.read_excel(r'C:\Users\USER\phase2project2\Official Website of National Center of Seismology.xlsx')
path

Official Website of National Center of Seismology Unnamed: 1 Unnamed: 2  \
0                                          Origin Time        Lat       Long   
1                              2019-05-12 00:21:04 IST      28.89      81.58   
2                              2019-05-12 07:42:38 IST       20.7      72.82   
3                              2019-05-12 23:00:01 IST       29.9       68.3   
4                              2019-05-15 07:59:35 IST        2.1      96.37   
...                                                ...        ...        ...   
1217                           2020-06-30 18:43:33 IST       38.9      76.21   
1218                           2020-06-30 21:53:52 IST       37.3       72.4   
1219                           2020-06-30 23:32:26 IST      33.16       76.3   
1220                           2020-07-01 02:57:53 IST      25.52      91.56   
1221                           2020-07-01 04:08:21 IST      26.33       92.5   

     Unnamed: 3 Unnamed: 4                                       Unnamed: 5  
0         Depth  Magnitude                                         Location  
1            30    4.3[ML]     153km ESE of Pithoragarh, Uttarakhand, India  
2             5    2.6[ML]                  52km S of Surat, Gujarat, India  
3            10    4.4[ML]                   524km S of Kabul , Afghanistan  
4            10    4.3[ML]                601km W of Kuala Lumpur, Malaysia  
...         ...        ...                                              ...  
1217         10    3.9[ML]                 462km SSE of Bishkek, Kyrgyzstan  
1218         20    3.4[ML]                 165km E of Fayzabad, Afghanistan  
1219          5    4.5[ML]  104km N of Dharamshala, Himachal Pradesh, India  
1220          8    2.9[ML]       32km NNW of Cherrapunjee, Meghalaya, India  
1221         19    2.6[MW]                  46km SW of Tezpur, Assam, India  

[1222 rows x 6 columns]

In [3]:
path.dtypes

Official Website of National Center of Seismology    object
Unnamed: 1                                           object
Unnamed: 2                                           object
Unnamed: 3                                           object
Unnamed: 4                                           object
Unnamed: 5                                           object
dtype: object

In [4]:
path=path.drop(['Official Website of National Center of Seismology'], axis = 1)
path

Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4  \
0           Lat       Long      Depth  Magnitude   
1         28.89      81.58         30    4.3[ML]   
2          20.7      72.82          5    2.6[ML]   
3          29.9       68.3         10    4.4[ML]   
4           2.1      96.37         10    4.3[ML]   
...         ...        ...        ...        ...   
1217       38.9      76.21         10    3.9[ML]   
1218       37.3       72.4         20    3.4[ML]   
1219      33.16       76.3          5    4.5[ML]   
1220      25.52      91.56          8    2.9[ML]   
1221      26.33       92.5         19    2.6[MW]   

                                           Unnamed: 5  
0                                            Location  
1        153km ESE of Pithoragarh, Uttarakhand, India  
2                     52km S of Surat, Gujarat, India  
3                      524km S of Kabul , Afghanistan  
4                   601km W of Kuala Lumpur, Malaysia  
...                                               ...  
1217                 462km SSE of Bishkek, Kyrgyzstan  
1218                 165km E of Fayzabad, Afghanistan  
1219  104km N of Dharamshala, Himachal Pradesh, India  
1220       32km NNW of Cherrapunjee, Meghalaya, India  
1221                  46km SW of Tezpur, Assam, India  

[1222 rows x 5 columns]

In [5]:
path=path.drop(['Unnamed: 5'], axis = 1)
path

Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
0           Lat       Long      Depth  Magnitude
1         28.89      81.58         30    4.3[ML]
2          20.7      72.82          5    2.6[ML]
3          29.9       68.3         10    4.4[ML]
4           2.1      96.37         10    4.3[ML]
...         ...        ...        ...        ...
1217       38.9      76.21         10    3.9[ML]
1218       37.3       72.4         20    3.4[ML]
1219      33.16       76.3          5    4.5[ML]
1220      25.52      91.56          8    2.9[ML]
1221      26.33       92.5         19    2.6[MW]

[1222 rows x 4 columns]

In [6]:
xyz=path.drop([0], axis = 0,inplace=True)
path

Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
1         28.89      81.58         30    4.3[ML]
2          20.7      72.82          5    2.6[ML]
3          29.9       68.3         10    4.4[ML]
4           2.1      96.37         10    4.3[ML]
5          7.48      94.33         10    4.8[ML]
...         ...        ...        ...        ...
1217       38.9      76.21         10    3.9[ML]
1218       37.3       72.4         20    3.4[ML]
1219      33.16       76.3          5    4.5[ML]
1220      25.52      91.56          8    2.9[ML]
1221      26.33       92.5         19    2.6[MW]

[1221 rows x 4 columns]

In [7]:
xyz

In [8]:
path

Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
1         28.89      81.58         30    4.3[ML]
2          20.7      72.82          5    2.6[ML]
3          29.9       68.3         10    4.4[ML]
4           2.1      96.37         10    4.3[ML]
5          7.48      94.33         10    4.8[ML]
...         ...        ...        ...        ...
1217       38.9      76.21         10    3.9[ML]
1218       37.3       72.4         20    3.4[ML]
1219      33.16       76.3          5    4.5[ML]
1220      25.52      91.56          8    2.9[ML]
1221      26.33       92.5         19    2.6[MW]

[1221 rows x 4 columns]

In [9]:
path.dtypes

Unnamed: 1    object
Unnamed: 2    object
Unnamed: 3    object
Unnamed: 4    object
dtype: object

In [10]:
y=path.iloc[:,-1].values


In [11]:

path

Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4
1         28.89      81.58         30    4.3[ML]
2          20.7      72.82          5    2.6[ML]
3          29.9       68.3         10    4.4[ML]
4           2.1      96.37         10    4.3[ML]
5          7.48      94.33         10    4.8[ML]
...         ...        ...        ...        ...
1217       38.9      76.21         10    3.9[ML]
1218       37.3       72.4         20    3.4[ML]
1219      33.16       76.3          5    4.5[ML]
1220      25.52      91.56          8    2.9[ML]
1221      26.33       92.5         19    2.6[MW]

[1221 rows x 4 columns]

In [12]:
y.dtype

dtype('O')

In [13]:
path=path.drop(['Unnamed: 4'], axis = 1)
path

Unnamed: 1 Unnamed: 2 Unnamed: 3
1         28.89      81.58         30
2          20.7      72.82          5
3          29.9       68.3         10
4           2.1      96.37         10
5          7.48      94.33         10
...         ...        ...        ...
1217       38.9      76.21         10
1218       37.3       72.4         20
1219      33.16       76.3          5
1220      25.52      91.56          8
1221      26.33       92.5         19

[1221 rows x 3 columns]

In [14]:
colname=path.columns

In [15]:
colname

Index(['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3'], dtype='object')

In [16]:
for col in colname:
    path[col]=path[col].astype(float)
path.dtypes

Unnamed: 1    float64
Unnamed: 2    float64
Unnamed: 3    float64
dtype: object

In [17]:
x=path

In [18]:
y

array(['4.3[ML]', '2.6[ML]', '4.4[ML]', ..., '4.5[ML]', '2.9[ML]',
       '2.6[MW]'], dtype=object)

In [19]:
yn=y[0:1]

In [20]:
yn

array(['4.3[ML]'], dtype=object)

In [21]:
y

array(['4.3[ML]', '2.6[ML]', '4.4[ML]', ..., '4.5[ML]', '2.9[ML]',
       '2.6[MW]'], dtype=object)

In [22]:
import array

In [23]:
arr=[]
for col in y:
    
    
    kl=y[0:1221]
    xyz=col[0:3]
    arr.append(xyz)
    

    
    
    
    
    
    



In [24]:
kkll=np.array(arr)

In [25]:
kkll.astype(float)

array([4.3, 2.6, 4.4, ..., 4.5, 2.9, 2.6])

In [26]:
kkll.dtype

dtype('<U3')

In [27]:
mno=path
mno

Unnamed: 1  Unnamed: 2  Unnamed: 3
1          28.89       81.58        30.0
2          20.70       72.82         5.0
3          29.90       68.30        10.0
4           2.10       96.37        10.0
5           7.48       94.33        10.0
...          ...         ...         ...
1217       38.90       76.21        10.0
1218       37.30       72.40        20.0
1219       33.16       76.30         5.0
1220       25.52       91.56         8.0
1221       26.33       92.50        19.0

[1221 rows x 3 columns]

In [28]:
kkll

array(['4.3', '2.6', '4.4', ..., '4.5', '2.9', '2.6'], dtype='<U3')

In [29]:
xl=mno
xl

Unnamed: 1  Unnamed: 2  Unnamed: 3
1          28.89       81.58        30.0
2          20.70       72.82         5.0
3          29.90       68.30        10.0
4           2.10       96.37        10.0
5           7.48       94.33        10.0
...          ...         ...         ...
1217       38.90       76.21        10.0
1218       37.30       72.40        20.0
1219       33.16       76.30         5.0
1220       25.52       91.56         8.0
1221       26.33       92.50        19.0

[1221 rows x 3 columns]

In [30]:
yl=kkll

In [31]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler(with_mean=False)
xll=sc.fit_transform(xl)
xll

array([[2.70538485, 7.64878734, 0.42093057],
       [1.93843774, 6.82746622, 0.07015509],
       [2.79996562, 6.40367952, 0.14031019],
       ...,
       [3.10524616, 7.15374447, 0.07015509],
       [2.38980344, 8.58449337, 0.11224815],
       [2.46565535, 8.672626  , 0.26658936]])

In [32]:
import joblib
joblib.dump(sc,'earthquakee')

['earthquakee']

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(xl,yl,test_size=0.3,random_state=0)

In [34]:
from sklearn.ensemble import RandomForestRegressor

In [35]:
mr= RandomForestRegressor(n_estimators=1000,criterion="mse",random_state=0)
mr.fit(x_train,y_train)

RandomForestRegressor(n_estimators=1000, random_state=0)

In [36]:
joblib.dump(mr,'earthquakee.save')

['earthquakee.save']

In [37]:
x_test

Unnamed: 1  Unnamed: 2  Unnamed: 3
1147       32.91       75.94        11.0
993        29.93       69.11        10.0
479        35.61       74.70        10.0
162        33.17       73.73        10.0
1156       28.82       76.74         7.0
...          ...         ...         ...
529        26.99       92.71        24.0
826        32.93       76.39         7.0
484        35.61       74.65        16.0
1213       37.12       71.13        97.0
580        36.85       91.59        10.0

[367 rows x 3 columns]

In [38]:
yl

array(['4.3', '2.6', '4.4', ..., '4.5', '2.9', '2.6'], dtype='<U3')

In [39]:
y_pred = mr.predict(x_test)
y_pred

array([3.4486, 3.8417, 4.0131, 3.8165, 2.5182, 3.9225, 4.5386, 4.0272,
       3.6221, 4.0137, 4.064 , 3.9203, 3.8707, 2.9876, 4.4578, 3.4795,
       3.1557, 4.1871, 4.4541, 4.3815, 3.836 , 3.963 , 4.5218, 3.2126,
       4.3323, 4.041 , 3.4822, 4.1635, 2.6278, 3.4492, 3.244 , 3.4642,
       4.2966, 3.9558, 3.7539, 4.4002, 3.6796, 3.6018, 4.0661, 4.004 ,
       4.1062, 3.2934, 4.4835, 4.1433, 4.0817, 3.3266, 4.5177, 4.5131,
       4.1696, 3.2368, 3.1428, 2.907 , 4.6827, 3.4174, 3.7219, 3.0414,
       4.6123, 3.6213, 3.2858, 2.553 , 4.0035, 4.4364, 2.9258, 4.3953,
       4.2821, 3.4026, 4.558 , 3.1719, 4.1587, 4.3255, 4.5412, 4.0814,
       4.0615, 4.0975, 3.4931, 3.3588, 3.3987, 3.4193, 4.1944, 3.3104,
       4.4643, 3.523 , 4.0122, 4.4922, 4.425 , 3.8217, 3.9121, 4.0249,
       3.0833, 3.9581, 3.1802, 4.0272, 4.1156, 2.7862, 4.4058, 4.0569,
       2.806 , 3.3186, 4.6515, 3.9959, 3.3864, 4.6763, 4.4142, 3.8512,
       3.2918, 4.1885, 3.3131, 4.3389, 4.0576, 4.1132, 3.728 , 3.0956,
      

In [40]:
a=mr.predict([[32.91,75.94,11.0]])
a

array([3.4486])

In [41]:
a=mr.predict([[29.93,69.11,10.0]])
a

array([3.8417])

In [42]:
a=mr.predict([[36.85,91.59,10.0]])
a

array([4.2366])

In [43]:
a=mr.predict([[32.91,75.94,11.0]])
a

array([3.4486])

In [44]:
a=mr.predict([[14.4644,75.9218,9.0]])
a

array([3.7823])

In [45]:
a=mr.predict([[3.2028,73.2207,35.0]])
a

array([4.4813])