In [1]:
# Import the libraries.

# Import pandas.
import pandas as pd
# Import numpy.
import numpy as np
# Import matplotlib.
import matplotlib.pyplot as plt
# Import seaborn.
import seaborn as sns
# Import regular expression.
import re
# import datetime.
import datetime as dt
# Import the data.


In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

In [3]:
df = pd.read_excel(r'C:\Users\USER\2projectworking\flood dataset (1).xlsx')
df

Unnamed: 0  Temp  Humidity  Cloud  ANNUAL  Jan-Feb  Mar-May  Jun-Sep  \
0             0    29        70     30  3248.6     73.4    386.2   2122.8   
1             1    28        75     40  3326.6      9.3    275.7   2403.4   
2             2    28        75     42  3271.2     21.7    336.3   2343.0   
3             3    29        71     44  3129.7     26.7    339.4   2398.2   
4             4    31        74     40  2741.6     23.4    378.5   1881.5   
..          ...   ...       ...    ...     ...      ...      ...      ...   
110         110    28        71     30  3035.1     66.2    313.5   2209.1   
111         111    29        71     37  2151.1     18.3    287.4   1535.6   
112         112    30        74     42  3255.4     43.9    218.5   2561.2   
113         113    31        71     31  3046.4     14.9    364.5   2164.8   
114         114    28        71     34  2600.6      8.9    465.9   1514.7   

     Oct-Dec     avgjune    sub  flood  
0      666.1  274.866667  649.9      0  
1      638.2  130.300000  256.4      1  
2      570.1  186.200000  308.9      0  
3      365.3  366.066667  862.5      0  
4      458.1  283.400000  586.9      0  
..       ...         ...    ...    ...  
110    446.3  262.833333  664.3      0  
111    309.8  143.433333  335.0      0  
112    431.8  347.566667  923.4      1  
113    502.1  151.466667  203.4      0  
114    611.1  187.866667  361.8      0  

[115 rows x 12 columns]

In [4]:
df=df.drop(['Unnamed: 0','sub','avgjune'], axis = 1)

In [5]:
df

Temp  Humidity  Cloud  ANNUAL  Jan-Feb  Mar-May  Jun-Sep  Oct-Dec  flood
0      29        70     30  3248.6     73.4    386.2   2122.8    666.1      0
1      28        75     40  3326.6      9.3    275.7   2403.4    638.2      1
2      28        75     42  3271.2     21.7    336.3   2343.0    570.1      0
3      29        71     44  3129.7     26.7    339.4   2398.2    365.3      0
4      31        74     40  2741.6     23.4    378.5   1881.5    458.1      0
..    ...       ...    ...     ...      ...      ...      ...      ...    ...
110    28        71     30  3035.1     66.2    313.5   2209.1    446.3      0
111    29        71     37  2151.1     18.3    287.4   1535.6    309.8      0
112    30        74     42  3255.4     43.9    218.5   2561.2    431.8      1
113    31        71     31  3046.4     14.9    364.5   2164.8    502.1      0
114    28        71     34  2600.6      8.9    465.9   1514.7    611.1      0

[115 rows x 9 columns]

In [6]:
df['Jan_May']=(df['Jan-Feb']+df['Mar-May'])/2
df['Jun_Dec']=(df['Jun-Sep']+df['Oct-Dec'])/2

In [7]:
df=df.drop(['Jan-Feb','Mar-May','Jun-Sep','Oct-Dec'], axis = 1)

In [8]:
df

Temp  Humidity  Cloud  ANNUAL  flood  Jan_May  Jun_Dec
0      29        70     30  3248.6      0   229.80  1394.45
1      28        75     40  3326.6      1   142.50  1520.80
2      28        75     42  3271.2      0   179.00  1456.55
3      29        71     44  3129.7      0   183.05  1381.75
4      31        74     40  2741.6      0   200.95  1169.80
..    ...       ...    ...     ...    ...      ...      ...
110    28        71     30  3035.1      0   189.85  1327.70
111    29        71     37  2151.1      0   152.85   922.70
112    30        74     42  3255.4      1   131.20  1496.50
113    31        71     31  3046.4      0   189.70  1333.45
114    28        71     34  2600.6      0   237.40  1062.90

[115 rows x 7 columns]

In [11]:
y=df.iloc[:,4:5].values
y

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [12]:
df

Temp  Humidity  Cloud  ANNUAL  flood  Jan_May  Jun_Dec
0      29        70     30  3248.6      0   229.80  1394.45
1      28        75     40  3326.6      1   142.50  1520.80
2      28        75     42  3271.2      0   179.00  1456.55
3      29        71     44  3129.7      0   183.05  1381.75
4      31        74     40  2741.6      0   200.95  1169.80
..    ...       ...    ...     ...    ...      ...      ...
110    28        71     30  3035.1      0   189.85  1327.70
111    29        71     37  2151.1      0   152.85   922.70
112    30        74     42  3255.4      1   131.20  1496.50
113    31        71     31  3046.4      0   189.70  1333.45
114    28        71     34  2600.6      0   237.40  1062.90

[115 rows x 7 columns]

In [13]:
x=df.drop(['flood'], axis = 1)

In [14]:
x

Temp  Humidity  Cloud  ANNUAL  Jan_May  Jun_Dec
0      29        70     30  3248.6   229.80  1394.45
1      28        75     40  3326.6   142.50  1520.80
2      28        75     42  3271.2   179.00  1456.55
3      29        71     44  3129.7   183.05  1381.75
4      31        74     40  2741.6   200.95  1169.80
..    ...       ...    ...     ...      ...      ...
110    28        71     30  3035.1   189.85  1327.70
111    29        71     37  2151.1   152.85   922.70
112    30        74     42  3255.4   131.20  1496.50
113    31        71     31  3046.4   189.70  1333.45
114    28        71     34  2600.6   237.40  1062.90

[115 rows x 6 columns]

In [15]:
y

array([[0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [21]:
# Import Decision Tree Classifier.
from sklearn.tree import DecisionTreeClassifier

# Import train-test split.
from sklearn.model_selection import train_test_split

# Import accuracy Score.
from sklearn.metrics import accuracy_score

#Import Recall Score.
from sklearn.metrics import recall_score 

#Import Precision Score.
from sklearn.metrics import precision_score 



In [22]:
from sklearn import preprocessing

In [23]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler(with_mean=False)
xl=sc.fit_transform(x)
xl

array([[25.95193221, 23.85187803,  6.9584742 ,  7.72973913,  2.9935679 ,
         7.18788887],
       [25.057038  , 25.5555836 ,  9.2779656 ,  7.91533282,  1.85632474,
         7.83917773],
       [25.057038  , 25.5555836 ,  9.74186388,  7.78351371,  2.33180441,
         7.50799206],
       [25.95193221, 24.19261914, 10.20576216,  7.44682773,  2.38456312,
         7.12242493],
       [27.74172064, 25.21484249,  9.2779656 ,  6.52338016,  2.61774356,
         6.02989881],
       [26.84682643, 23.85187803,  8.81406732,  6.44343211,  1.72019426,
         6.29871333],
       [25.95193221, 25.21484249,  9.2779656 ,  8.73503827,  2.29076987,
         8.55541507],
       [26.84682643, 26.57780694,  8.35016904,  6.30138156,  2.0354438 ,
         6.02010499],
       [26.84682643, 24.19261914,  9.2779656 ,  7.25766493,  4.52161627,
         6.07190913],
       [26.84682643, 23.85187803,  7.88627076,  6.77797663,  2.11751289,
         6.50386803],
       [25.057038  , 24.87410137,  6.9584742 ,  6.

In [24]:
import joblib
joblib.dump(sc,'floodsk')

['floodsk']

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [26]:
from sklearn.ensemble import RandomForestRegressor

In [27]:
mr= RandomForestRegressor(n_estimators=1000,criterion="mse",random_state=0)
mr.fit(x_train,y_train)

<ipython-input-27-84cba359e344>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  mr.fit(x_train,y_train)


RandomForestRegressor(n_estimators=1000, random_state=0)

In [28]:
joblib.dump(mr,'floods.save')

['floods.save']

In [29]:
y_pred = mr.predict(x_test)
y_pred

array([0.   , 0.931, 0.   , 0.   , 0.   , 0.   , 0.624, 0.   , 0.984,
       0.   , 0.335, 0.084, 0.889, 0.581, 0.001, 0.   , 0.   , 0.   ,
       0.793, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 0.   , 0.002, 0.97 , 0.002, 0.   , 0.99 ])

In [32]:
df

Temp  Humidity  Cloud  ANNUAL  flood  Jan_May  Jun_Dec
0      29        70     30  3248.6      0   229.80  1394.45
1      28        75     40  3326.6      1   142.50  1520.80
2      28        75     42  3271.2      0   179.00  1456.55
3      29        71     44  3129.7      0   183.05  1381.75
4      31        74     40  2741.6      0   200.95  1169.80
..    ...       ...    ...     ...    ...      ...      ...
110    28        71     30  3035.1      0   189.85  1327.70
111    29        71     37  2151.1      0   152.85   922.70
112    30        74     42  3255.4      1   131.20  1496.50
113    31        71     31  3046.4      0   189.70  1333.45
114    28        71     34  2600.6      0   237.40  1062.90

[115 rows x 7 columns]

In [33]:
a=mr.predict([[29,70,30,3248,229,1394]])
a

array([0.])

In [34]:
a=mr.predict([[29,71,30,3035,189,1327]])
a

array([0.])

In [35]:
a=mr.predict([[30,71,42,3255,131,1496]])
a

array([0.807])

In [36]:
df

Temp  Humidity  Cloud  ANNUAL  flood  Jan_May  Jun_Dec
0      29        70     30  3248.6      0   229.80  1394.45
1      28        75     40  3326.6      1   142.50  1520.80
2      28        75     42  3271.2      0   179.00  1456.55
3      29        71     44  3129.7      0   183.05  1381.75
4      31        74     40  2741.6      0   200.95  1169.80
..    ...       ...    ...     ...    ...      ...      ...
110    28        71     30  3035.1      0   189.85  1327.70
111    29        71     37  2151.1      0   152.85   922.70
112    30        74     42  3255.4      1   131.20  1496.50
113    31        71     31  3046.4      0   189.70  1333.45
114    28        71     34  2600.6      0   237.40  1062.90

[115 rows x 7 columns]

In [37]:
a=mr.predict([[29,73.7,78.42,3200,229,1394]])
a

array([0.002])

In [ ]:
a=mr.predict([[14.4644,75.9218,1000,180,133.33,346,30.33]])
a

In [ ]:
a=mr.predict([[74.4644,45.9218,1000,180,133.33,346,30.33]])
a